# vpype read input.svg gwrite output.gcode

# G21 - set to mm
# G17 - set XY plane
# G90 - set to absolute positioning
# G54 - set to G54 workspace
# G0 - rapid move
# G1 - controlled move
# G4 P1.0 - wait 1.0s
# G00 Z1 - activate solenoid (pen up)
# G00 Z0 - deactivate solenoid (pen down)

[gwrite]
default_profile = "plotterxy"

[gwrite.plotterxy]
document_start = "G17 G21 G90 G54\n"
segment_first = "G00 X{x:.2f} Y{y:.2f}\nG00 Z0\nG4 P0.250\n"
segment = "G01 X{x:.2f} Y{y:.2f} F5000\n"
segment_last = "G01 X{x:.2f} Y{y:.2f} F5000\nG00 Z1\n"
document_end = ""
unit = "mm"
invert_y = "True"
