# vpype read input.svg gwrite output.gcode

# G21 - set to mm
# G17 - set XY plane
# G90 - set to absolute positioning
# G54 - set to G54 workspace
# G0 - rapid move
# G1 - controlled move
# G4 P1.0 - wait 1.0s
# M3 - enable solenoid output
# M5 - disable solenoid output
# G01 Z1 F1000- activate solenoid
# G01 Z0 F1000 - deactivate solenoid

[gwrite]
default_profile = "plotterxy"

[gwrite.plotterxy]
document_start = "G17 G21 G90 G54\n"
segment_first = "G00 X{x:.2f} Y{y:.2f}\nG01 Z-3.00 F800\nG4 P0.010\n"
segment = "G01 X{x:.2f} Y{y:.2f} F3000\n"
segment_last = "G01 X{x:.2f} Y{y:.2f} F3000\nG01 Z0.00 F800\nG4 P0.010\n"
document_end = ""
unit = "mm"
invert_y = "True"
invert_x = "True"

