board: MKS-DLC32
name: K40 MOD
meta: 2022-12-27 by Tong

kinematics:
  corexy:

stepping:
  engine: I2S_STREAM
#Static only, Stream Produces a second "ghost line" when doing engraving/Filling
# 255 keeps motors neabled at all times
  idle_ms: 255
  pulse_us: 6
  dir_delay_us: 10
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 78.750
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 440.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 700.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:low
      hard_limits: true
      pulloff_mm: 6.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:low


  y:
    steps_per_mm: 78.750
    max_rate_mm_per_min: 3000.000
    acceleration_mm_per_sec2: 1000.000
    max_travel_mm: 320.000
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 700.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:low
      hard_limits: true
      pulloff_mm: 6.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:low

  z:
    steps_per_mm: 50.000
    max_rate_mm_per_min: 800.000
    acceleration_mm_per_sec2: 800.000
    max_travel_mm: 8.000
    soft_limits: true
    homing:
      cycle: 0
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 50.000
      seek_mm_per_min: 50.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_pos_pin: gpio.34:low
      hard_limits: true
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: gpio.39

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: NO_PIN

start:
  must_home: false

# 5,18,19,22,23,25,26,27,32,33,39,I2SO.7
# SDA 0 / SCL 4
